# Generated by Django 5.1.2 on 2025-11-27 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='funcionario',
        ),
    ]
